version: "3"

networks:
  traefik2_proxy:
    external:
      name: traefik2_proxy
  default:
    driver: bridge

services:

  db:
    image: mariadb
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    container_name: nextcloud-mariadb
    env_file:
      - ./nc.env
    volumes:
      - ${USERDIR}/docker/nextcloud/mysql:/var/lib/mysql
    restart: unless-stopped
    networks:
      - default

  redis:
    image: redis:alpine
    container_name: redis
    env_file:
      - ./nc.env
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    restart: unless-stopped
    volumes:
      - ${USERDIR}/docker/nextcloud/redis:/data
    networks:
      - default

  nextcloud:
    image: nextcloud:20.0.5
    container_name: nextcloud
    env_file:
      - ./nc.env
    restart: unless-stopped
    networks:
      - traefik2_proxy
      - default
    security_opt:
      - no-new-privileges:true
    depends_on:
      - db
      - redis
    volumes:
      - ${USERDIR}/docker/nextcloud/nextcloud:/var/www/html
      - ${USERDIR}/docker/nextcloud/config:/var/www/html/config
      - ${USERDIR}/docker/nextcloud/custom_apps:/var/www/html/custom_apps
      - ${USERDIR}/docker/nextcloud/data:/var/www/html/data
      - ${USERDIR}/docker/nextcloud/themes:/var/www/html/themes
    environment:
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud,nextcloud_redirect"
      # - "traefik.http.middlewares.nextcloud.headers.hostsproxyheaders=X-Forwarded-Host"
      # - "traefik.http.middlewares.nextcloud.headers.sslredirect=true"
      # - "traefik.http.middlewares.nextcloud.headers.sslhost=$DOMAINNAME" 
      # - "traefik.http.middlewares.nextcloud.headers.sslforcehost=true"
      - "traefik.http.middlewares.nextcloud.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.nextcloud.headers.sslproxyheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.nextcloud.headers.stsseconds=31536000"
      - "traefik.http.middlewares.nextcloud.headers.stsincludesubdomains=true"
      - "traefik.http.middlewares.nextcloud.headers.stspreload=true"
      - "traefik.http.middlewares.nextcloud.headers.forcestsheader=true"
      - "traefik.http.middlewares.nextcloud.headers.browserXssFilter=true"
      # - "traefik.http.middlewares.nextcloud.headers.framedeny=true"
#      - "traefik.http.middlewares.nextcloud.headers.customframeoptionsvalue=SAMEORIGIN" # This option overrides FrameDeny
      # - "traefik.http.middlewares.nextcloud.headers.contenttypenosniff=true"
      # - "traefik.http.middlewares.nextcloud.headers.browserxssfilter=true"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.$DOMAINNAME`)" #comment out if using dyndns
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.regex=https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nextcloud_redirect.redirectregex.permanent=true"
      - "traefik.http.routers.nextcloud.tls=true"
      # - "traefik.http.routers.nextcloud.middlewares=chain-no-auth@file"


      # - "traefik.enable=true"
      # - "traefik.backend=nextcloud"
      # - "traefik.frontend.rule=Host:nextcloud.${DOMAINNAME}"
      # - "traefik.port=80"
      # - "traefik.protocol=http"
      # - "traefik.docker.network=traefik_proxy"
      # - "traefik.frontend.headers.SSLRedirect=true"
      # - "traefik.frontend.headers.STSSeconds=315360000"
      # - "traefik.frontend.headers.browserXSSFilter=true"
      # - "traefik.frontend.headers.contentTypeNosniff=true"
      # - "traefik.frontend.headers.forceSTSHeader=true"
      # - "traefik.frontend.headers.SSLHost=sherma.net"
      # - "traefik.frontend.headers.STSIncludeSubdomains=true"
      # - "traefik.frontend.headers.STSPreload=true"
      # - "traefik.frontend.redirect.permanent=true"
      # - "traefik.frontend.redirect.regex=https://(.*)/.well-known/(card|cal)dav"
      # - "traefik.frontend.redirect.replacement=https://$$1/remote.php/dav/"
#      - "traefik.frontend.headers.frameDeny: true" #customFrameOptionsValue overrides this
    #   - "traefik.frontend.headers.customFrameOptionsValue: allow-from https:${DOMAINNAME}"

  cron:
    image: nextcloud:20.0.5
    env_file:
      - ./nc.env
    restart: unless-stopped
    volumes:
      - ${USERDIR}/docker/nextcloud/nextcloud:/var/www/html
      - ${USERDIR}/docker/nextcloud/config:/var/www/html/config
      - ${USERDIR}/docker/nextcloud/data:/var/www/html/data
      - ${USERDIR}/docker/nextcloud/custom_apps:/var/www/html/custom_apps
      - ${USERDIR}/docker/nextcloud/themes:/var/www/html/themes
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis
    networks:
      - default
